
# 入力データの特徴量の順番
input_data:
  feature_order:
    - chiba_temperature
    - gumma_temperature
    - ibaraki_temperature
    - kanagawa_temperature
    - saitama_temperature
    - tochigi_temperature
    - tokyo_temperature
    - yamanashi_temperature
    - hour_sin
    - hour_cos
    - day_of_week_sin
    - day_of_week_cos
    - day_of_year_sin
    - day_of_year_cos
    - chiba_temperature_lag1
    - chiba_temperature_lag2
    - chiba_temperature_lag3
    - chiba_temperature_delta_lag1
    - gumma_temperature_lag1
    - gumma_temperature_lag2
    - gumma_temperature_lag3
    - gumma_temperature_delta_lag1
    - ibaraki_temperature_lag1
    - ibaraki_temperature_lag2
    - ibaraki_temperature_lag3
    - ibaraki_temperature_delta_lag1
    - kanagawa_temperature_lag1
    - kanagawa_temperature_lag2
    - kanagawa_temperature_lag3
    - kanagawa_temperature_delta_lag1
    - saitama_temperature_lag1
    - saitama_temperature_lag2
    - saitama_temperature_lag3
    - saitama_temperature_delta_lag1
    - tochigi_temperature_lag1
    - tochigi_temperature_lag2
    - tochigi_temperature_lag3
    - tochigi_temperature_delta_lag1
    - tokyo_temperature_lag1
    - tokyo_temperature_lag2
    - tokyo_temperature_lag3
    - tokyo_temperature_delta_lag1
    - yamanashi_temperature_lag1
    - yamanashi_temperature_lag2
    - yamanashi_temperature_lag3
    - yamanashi_temperature_delta_lag1
    - chiba_temperature_sma3
    - chiba_temperature_sma5
    - chiba_temperature_delta_sma3
    - chiba_temperature_delta_sma5
    - gumma_temperature_sma3
    - gumma_temperature_sma5
    - gumma_temperature_delta_sma3
    - gumma_temperature_delta_sma5
    - ibaraki_temperature_sma3
    - ibaraki_temperature_sma5
    - ibaraki_temperature_delta_sma3
    - ibaraki_temperature_delta_sma5
    - kanagawa_temperature_sma3
    - kanagawa_temperature_sma5
    - kanagawa_temperature_delta_sma3
    - kanagawa_temperature_delta_sma5
    - saitama_temperature_sma3
    - saitama_temperature_sma5
    - saitama_temperature_delta_sma3
    - saitama_temperature_delta_sma5
    - tochigi_temperature_sma3
    - tochigi_temperature_sma5
    - tochigi_temperature_delta_sma3
    - tochigi_temperature_delta_sma5
    - tokyo_temperature_sma3
    - tokyo_temperature_sma5
    - tokyo_temperature_delta_sma3
    - tokyo_temperature_delta_sma5
    - yamanashi_temperature_sma3
    - yamanashi_temperature_sma5
    - yamanashi_temperature_delta_sma3
    - yamanashi_temperature_delta_sma5
    - chiba_precipitation
    - gumma_precipitation
    - ibaraki_precipitation
    - kanagawa_precipitation
    - saitama_precipitation
    - tochigi_precipitation
    - tokyo_precipitation
    - yamanashi_precipitation
    - chiba_sunshine_duration
    - gumma_sunshine_duration
    - ibaraki_sunshine_duration
    - kanagawa_sunshine_duration
    - saitama_sunshine_duration
    - tochigi_sunshine_duration
    - tokyo_sunshine_duration
    - yamanashi_sunshine_duration
    - chiba_dew_point
    - gumma_dew_point
    - ibaraki_dew_point
    - kanagawa_dew_point
    - saitama_dew_point
    - tochigi_dew_point
    - tokyo_dew_point
    - yamanashi_dew_point
    - chiba_vapor_pressure
    - gumma_vapor_pressure
    - ibaraki_vapor_pressure
    - kanagawa_vapor_pressure
    - saitama_vapor_pressure
    - tochigi_vapor_pressure
    - tokyo_vapor_pressure
    - yamanashi_vapor_pressure
    - chiba_humidity
    - gumma_humidity
    - ibaraki_humidity
    - kanagawa_humidity
    - saitama_humidity
    - tochigi_humidity
    - tokyo_humidity
    - yamanashi_humidity
    - chiba_weather
    - gumma_weather
    - ibaraki_weather
    - kanagawa_weather
    - saitama_weather
    - tochigi_weather
    - tokyo_weather
    - yamanashi_weather
    - chiba_visibility
    - gumma_visibility
    - ibaraki_visibility
    - kanagawa_visibility
    - saitama_visibility
    - tochigi_visibility
    - tokyo_visibility
    - yamanashi_visibility
