# fastAPIで動かすコンテナ
# Build command : docker build -f Dockerfile.api -t predict-api .
# Run command: docker run --rm -p 8000:8000 predict-api
# --rmはコンテナが停止した瞬間に自動でコンテナごと消滅する。不要なコンテナをためない。

FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libgomp1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]